### ISSUE TITLE
Enterprise Changed

### ISSUE THREAD

**Issue by pas0030376** [pas0030376/EmpresasyPracticas#15]
Empresa: Nom, CIF, adreça, municipi, CP (poden ser a Catalunya o fora de Catalunya, les Erasmus) i telèfon
Persona responsable: nom i cognoms, DNI, càrrec, telèfon i email
Tutor/tutora d'empresa:  nom i cognoms, DNI, càrrec, telèfon i email

**Comment by Rachelitaa** [comment]
Hecho. Nuevos campos añadidos a la tabla Empresa.
