### ISSUE TITLE
Do not show "Encara no s'ha respos ...." For students done w/ practica AND had received the email

### ISSUE THREAD

**Issue by zajustine** [pas0030376/EmpresasyPracticas#2]
![whatsapp image 2018-03-09 at 4 05 51 pm](https://user-images.githubusercontent.com/32771389/37214384-3718a926-23b5-11e8-8e81-8910b5ecbda7.jpeg)

It should only be shown for student's who haven't ANSWERED the ENQUESTA. Otherwise, the comments will be displayed.

**Comment by pas0030376** [comment]
Fixed
