### ISSUE TITLE
Enric Request

### ISSUE THREAD

**Issue by pas0030376** [pas0030376/EmpresasyPracticas#7]
Després de parlar-ho amb la direcció, hem vist que el prototip hauria de tenir a la pantalla principal "Alumnat", "Empreses" i "Centre".

**Comment by zajustine** [comment]
@Rachelitaa 
Hello Rachelita maybe you could email sr Enric to ask him what does he want to see/view in the _**Centre**_. It's unclear for the moment and we can't move on from this if we don't know what to display.
